### ISSUE TITLE
HOW TO SET UP A NODE

### ISSUE THREAD

**Issue by 0RIBER0** [aklciot/TTGO-Gateway-repeater#5]

**Comment by aklciot** [comment]
Please provide a fault description.

WD

**Comment by 0RIBER0** [comment]
thanks for your response, my question is: if there is guide to connect a node to the gateway

**Comment by aklciot** [comment]
Not exactly, heres a link to an example sensor and guide that works with the gateway.

https://github.com/aklciot/StreamECSensor

This sensor code contains everything needed to connect to the gateway.  Data will appear in your MQTT queue. I am using node red to process the data.

I'll add a stripped down simplified sample code for the node to this repo and post it here.

**Comment by aklciot** [comment]
Example node code is now uploaded here:

https://github.com/aklciot/TTGO-Gateway-repeater/blob/master/NodeExampleUltraSonicSensor.ino
